
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwoushehuukarwclelzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3b3VzaGVodXVrYXJ3Y2xlbHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjQwOTQsImV4cCI6MjA1OTgwMDA5NH0.NgECJNXT6SluQONGCrdcdvxj_9koGYmfNSCUT-JMhBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'X-Client-Info': 'supabase-js-web',
      },
    },
    // Set proper storage configuration
    storage: {
      // Set long-lived caching for static assets
      persistSession: true
    }
  }
);
